trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
pr:
  autoCancel: false
  branches:
    include:
    - master

resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: theohbrothers                   # Check for your 'Type: Github' connection under 'Project Settings' > 'Service connections'
    ref: refs/tags/v0.7.0
  - repository: PSRepositoryReleaseManager
    type: github
    name: theohbrothers/PSRepositoryReleaseManager
    endpoint: theohbrothers
    ref: refs/tags/v0.8.0

stages:
- stage: build_test
  displayName: Build, Test
  jobs:
  - job: windows_pwsh
    displayName: '[Windows] PowerShell Core'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/build-test.yml@PSModulePublisher
  - job: windows_2019
    displayName: '[Windows Server 2019] PowerShell Core'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/build-test.yml@PSModulePublisher
  - job: windows_powershell_5_1
    displayName: '[Windows] PowerShell 5.1'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/build-test.yml@PSModulePublisher
  - job: windows_powershell_5_1_windows_2019
    displayName: '[Windows Server 2019] PowerShell 5.1'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/build-test.yml@PSModulePublisher
- stage: build_publish
  displayName: Build, Publish
  dependsOn: build_test
  jobs:
  - job: windows_powershell_5_1
    displayName: '[Windows] PowerShell 5.1'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/build-publish.yml@PSModulePublisher
- stage: release
  displayName: Release
  dependsOn: build_publish
  jobs:
  - job: linux_container
    displayName: '[Linux] [Container] PowerShell Core'
    pool:
      vmImage: ubuntu-22.04
    container: joeltimothyoh/powershell:7.3.9-ubuntu-22.04-git
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/generate.yml@PSRepositoryReleaseManager
    - template: templates/azure-pipelines/entrypoint/release.yml@PSRepositoryReleaseManager
