trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr:
  autoCancel: false
  branches:
    include:
    - '*'

resources:
  repositories:
  - repository: PSModulePublisher
    type: github
    name: theohbrothers/PSModulePublisher
    endpoint: theohbrothers                   # Check for your 'Type: Github' connection under 'Project Settings' > 'Service connections'
    ref: refs/tags/v0.3.4
  - repository: PSRepositoryReleaseManager
    type: github
    name: theohbrothers/PSRepositoryReleaseManager
    endpoint: theohbrothers
    ref: refs/tags/v0.6.1

stages:
- stage: build_test
  displayName: Build, Test
  jobs:
  - job: windows_pwsh
    displayName: '[Windows] PowerShell Core'
    pool:
      vmImage: windows-2022
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/continuous-build.yml@PSModulePublisher
  - job: windows_2019
    displayName: '[Windows Server 2019] PowerShell Core'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/continuous-build.yml@PSModulePublisher
  - job: windows_powershell_5_1
    displayName: '[Windows] PowerShell 5.1'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/continuous-build.yml@PSModulePublisher
- stage: publish
  displayName: Publish
  dependsOn: build_test
  jobs:
  - job: windows_powershell_5_1
    displayName: '[Windows] PowerShell 5.1'
    pool:
      vmImage: windows-2019
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/windows/powershell/continuous-build.yml@PSModulePublisher
    - template: templates/azure-pipelines/entrypoint/windows/powershell/publish.yml@PSModulePublisher
- stage: release
  displayName: Release
  dependsOn: publish
  jobs:
  - job: linux_container
    displayName: '[Linux] [Container] PowerShell Core'
    pool:
      vmImage: ubuntu-18.04
    container: joeltimothyoh/powershell:6.1.0-ubuntu-18.04-git
    steps:
    - checkout: self
      submodules: recursive
    - template: templates/azure-pipelines/entrypoint/generate.yml@PSRepositoryReleaseManager
    - template: templates/azure-pipelines/entrypoint/release.yml@PSRepositoryReleaseManager
